#!/usr/bin/env ruby
# frozen_string_literal: true

libs = []
libs << './config/environment.rb'

command_line = []
command_line << 'pry'
command_line << libs.inject('') { |acc, lib| acc + %( -r "#{lib}") }
command = command_line.join(' ')

puts 'Welcome to the console interface.'
exec command
